GET http://localhost:3000/bucketlist
###
GET http://localhost:3000/bucketlist/628f76805a1d82fe2575455f


### CREATE
POST http://localhost:3000/bucketlist
content-type: application/json

{
  "name":"Get wrecked",
  "deadline":"2031",
  "priority":"1",
  "description":"I want to get destroyed",
  "plan":"Pit myself against the strongest",
  "links":"wikipedia.com/wreckage",
  "notes":"It'll be a learning experience"
}

###UPDATE
PUT http://localhost:3000/bucketlist/628f76805a1d82fe2575455f
content-type: application/json

{
  "name":"Get Wrekt",
  "deadline":"2024",
  "priority":"1",
  "description":"I want to get destroyed",
  "plan":"Pit myself against the strongest",
  "links":"wikipedia.com/wreckage",
  "notes":"It'll be a learning experience"
}

###DELETE
DELETE http://localhost:3000/bucketlist/62881419657e874e70f0f0ff






###HEROKU__________________________________________

GET https://cse341-project2-suggs.herokuapp.com/bucketlist
###
GET https://cse341-project2-suggs.herokuapp.com/bucketlist/628653719d28ed899b9b04ec

### CREATE
POST https://cse341-project2-suggs.herokuapp.com/bucketlist
content-type: application/json

{
  "name":"Get wrecked",
  "deadline":"2031",
  "priority":"1",
  "description":"I want to get destroyed",
  "plan":"Pit myself against the strongest",
  "links":"wikipedia.com/wreckage",
  "notes":"It'll be a learning experience"
}

###UPDATE
PUT http://cse341-project2-suggs.herokuapp.com/bucketlist/628653719d28ed899b9b04ec
content-type: application/json

{
  "name":"Get Wrekt",
  "deadline":"2024",
  "priority":"1",
  "description":"I want to get destroyed",
  "plan":"Pit myself against the strongest",
  "links":"wikipedia.com/wreckage",
  "notes":"It'll be a learning experience"
}

###DELETE
DELETE http://cse341-project2-suggs.herokuapp.com/bucketlist/628653719d28ed899b9b04ec